name: cicd
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-static-i18n
      - run: pip install mkdocs-render-swagger-plugin
#      - run: pip install mike
#      - run: mike deploy 1.0.0 -p --rebase
#      - run: mike set-default 1.0.0 -p --rebase
      - run: mkdocs gh-deploy --force
